In [39]:
import tt

In [2]:
import numpy as np

In [33]:
tens = np.empty([3, 4, 5, 6, 7, 8], order="F")

# fill
for i0 in range(tens.shape[0]):
    for i1 in range(tens.shape[1]):
        for i2 in range(tens.shape[2]):
            for i3 in range(tens.shape[3]):
                for i4 in range(tens.shape[4]):
                    for i5 in range(tens.shape[5]):
                        tens[i0, i1, i2, i3, i4, i5] = i0 + i1 + i2 + i3 + i4 + i5

In [40]:
tens_tt = tt.vector(tens, 1e-12)

In [45]:
tt.vector.to_list(tens_tt)

[array([[[-1.07379263e+03,  2.38619639e+01],
         [-1.15252719e+03,  1.03941073e+00],
         [-1.23126175e+03, -2.17831424e+01]]]),
 array([[[ 0.44716414,  0.01496792],
         [ 0.48133852,  0.00553208],
         [ 0.51551289, -0.00390376],
         [ 0.54968727, -0.01333959]],
 
        [[ 0.18850523, -0.52962457],
         [ 0.07060849, -0.49707228],
         [-0.04728825, -0.46451999],
         [-0.16518499, -0.4319677 ]]]),
 array([[[ 0.38365971, -0.01661869],
         [ 0.4143151 , -0.00885468],
         [ 0.4449705 , -0.00109067],
         [ 0.47562589,  0.00667334],
         [ 0.50628129,  0.01443735]],
 
        [[-0.23935333, -0.47273071],
         [-0.1283267 , -0.44461129],
         [-0.01730007, -0.41649187],
         [ 0.09372655, -0.38837245],
         [ 0.20475318, -0.36025303]]]),
 array([[[ 0.33508874, -0.01655273],
         [ 0.3631676 , -0.01044522],
         [ 0.39124646, -0.0043377 ],
         [ 0.41932532,  0.00176982],
         [ 0.44740418,  0.00787733],