In [1]:
import tt

In [2]:
import numpy as np

In [26]:
tens = np.empty([3, 4, 5, 6, 7, 8], order="F")

# fill
for i0 in range(tens.shape[0]):
    for i1 in range(tens.shape[1]):
        for i2 in range(tens.shape[2]):
            for i3 in range(tens.shape[3]):
                for i4 in range(tens.shape[4]):
                    for i5 in range(tens.shape[5]):
                        tens[i0, i1, i2, i3, i4, i5] = i0 + i1 + i2 + i3 + i4 + i5

In [19]:
tens = np.empty([3, 4, 5], order="F")

# fill
for i0 in range(tens.shape[0]):
    for i1 in range(tens.shape[1]):
        for i2 in range(tens.shape[2]):
            tens[i0, i1, i2] = i0 + i1 + i2

In [37]:
tens = np.empty([3, 4], order="F")

# fill
for i0 in range(tens.shape[0]):
    for i1 in range(tens.shape[1]):
        tens[i0, i1] = i0 + i1

In [38]:
tens_tt = tt.vector(tens, 1e-14)
tens_tt

This is a 2-dimensional tensor 
r(0)=1, n(0)=3 
r(1)=2, n(1)=4 
r(2)=1 

In [39]:
l = tt.vector.to_list(tens_tt)

In [40]:
for i, x in enumerate(l):
    print(f"core {i}\nshape={x.shape}\n{x}")

core 0
shape=(1, 3, 2)
[[[-3.62420537  0.93012658]
  [-5.47455428  0.17104232]
  [-7.32490319 -0.58804193]]]
core 1
shape=(2, 4, 1)
[[[-0.20798263]
  [-0.37771903]
  [-0.54745543]
  [-0.71719183]]

 [[-0.81039696]
  [-0.39664636]
  [ 0.01710423]
  [ 0.43085483]]]
